#ifndef LOCATIONREFERENCE_H
#define LOCATIONREFERENCE_H

/*
    This is a file that stores large arrays of information needed
    to parse location, without needing hundreds of lines before the code 
    starts in the location parsing module.
*/


#include <unistd.h>
#include <stdlib.h>
#include <string.h>

// number of states stored
#define PARLOCNUMSTATES 64
// number of multi-state cue words
#define PARLOCNUMMULTISTATES 11
// number of misspellings
#define PARLOCALTLEN 32
// number of street suffixes
#define PARLOCSTRSUFS 569
// number of street directionals (N, NW, SW, ETC)
#define PARLOCSTRDIRS 24
// number of valid country spellings
#define PARLOCCOUNTRIES 5
// number of major cities in list
#define PARLOCCITIES 486
// number of cues for major multicities of length 2
#define PARLOCMULTWOCITYCUES 81
// number of cues for major multicities of length 3
#define PARLOCMULTTHRCITYCUES 9


/* An array of US States and Canadian Provinces
   Each state abbreviation is next to its full name
   For normalization purposes, when storing state, we should 
   store this information as the two letter code.

   From the array, we just subtract one from odd indices
*/
const char* states [] = {   "AL", "ALABAMA", 
                            "AK", "ALASKA", 
                            "AZ", "ARIZONA", 
                            "AR", "ARKANSAS", 
                            "CA", "CALIFORNIA", 
                            "CO", "COLORADO", 
                            "CT", "CONNECTICUT", 
                            "DE", "DELAWARE", 
                            "DC", "DISTRICT OF COLUMBIA",
                            "FL", "FLORIDA", 
                            "GA", "GEORGIA", 
                            "HI", "HAWAII",
                            "ID", "IDAHO", 
                            "IL", "ILLINOIS", 
                            "IN", "INDIANA", 
                            "IA", "IOWA", 
                            "KS", "KANSAS",
                            "KY", "KENTUCKY", 
                            "LA", "LOUISIANA", 
                            "ME", "MAINE", 
                            "MD", "MARYLAND", 
                            "MA", "MASSACHUSETTS", 
                            "MI", "MICHIGAN", 
                            "MN", "MINNESOTA", 
                            "MS", "MISSISSIPPI", 
                            "MO", "MISSOURI",
                            "MT", "MONTANA",
                            "NE", "NEBRASKA",
                            "NV", "NEVADA",
                            "NH", "NEW HAMPSHIRE", 
                            "NJ", "NEW JERSEY",
                            "NM", "NEW MEXICO",
                            "NY", "NEW YORK",
                            "NC", "NORTH CAROLINA",
                            "ND", "NORTH DAKOTA",
                            "OH", "OHIO",
                            "OK", "OKLAHOMA",
                            "OR", "OREGON",
                            "PA", "PENNSYLVANIA", 
                            "RI", "RHODE ISLAND",
                            "SC", "SOUTH CAROLINA",
                            "SD", "SOUTH DAKOTA",
                            "TN", "TENNESSEE", 
                            "TX", "TEXAS",
                            "UT", "UTAH",
                            "VT", "VERMONT",
                            "VA", "VIRGINIA", 
                            "WA", "WASHINGTON",
                            "WV", "WEST VIRGINIA", 
                            "WI", "WISCONSIN", 
                            "WY", "WYOMING",
                            "AB", "ALBERTA",
                            "BC", "BRITISH COLUMBIA",
                            "MB", "MANITOBA",
                            "NB", "NEW BRUNSWICK",
                            "NL", "NEWFOUNDLAND AND LABRADOR",
                            "NS", "NOVA SCOTIA",
                            "NT", "NORTHWEST TERRITORIES",
                            "NU", "NUNAVUT", // NEW
                            "ON", "ONTARIO",
                            "PE", "PRINCE EDWARD ISLAND", 
                            "QC", "QUEBEC",
                            "SK", "SASKATCHEWAN", 
                            "YT", "YUKON"
                        };


// for state/province/territory names that are not
const char* multistateCue [] = { "DISTRICT", "NEW", "NORTH", "RHODE", "SOUTH", "WEST", "BRITISH", "NEWFOUNDLAND",
                                    "NOVA", "NORTHWEST", "PRINCE"};

// the number of words in the above strings' corresponding names
// we are greatly benefitted by that any prefixes that have more than one corresponding state
// all share the same number of words. This implementation must be changed then if states is updated
const int multistateCueLength [] = { 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3 };

// An array of common state and province misspellings or alternate names
const char* alternateStates [] = {  "CONNETICUT", 
                                    "DISTRICT OF COLOMBIA",
                                    "HAWAI\'I", "HAWIIA", 
                                    "LOUISIANNA",
                                    "MASSACHUSSETTS", "MASSECHUSSETS", "MASSECHUSETTS", "MASSECHUSSETTS", 
                                    "MISSISIPPI", "MISISSIPPI", "MISSISSIPI", "MISISIPPI", "MISISSIPI", 
                                        "MISSISIPI", "MISISIPI",
                                    "NEW HAMSHIRE",
                                    "PENSYLVANIA", 
                                    "TENESSEE", "TENNESEE",
                                    "VIRGINNIA",
                                    "WEST VIRGINNIA",
                                    "WISCONSON",
                                    "PRINCE EDWARD",
                                    "SASKETCHEWAN", "SASKATCHAWAN", "SASKETCHAWAN",
                                    "NEWFOUNDLAND", "LABRADOR",
                                    "NONAVUT", "NUNAVIT", "NONAVIT"
                                };

// This array stores the canonical names of the misspellings above
// So for instance 
/* 
    alternateStates[2] = "HAWIIA"
    which maps to
    alternateStatesCanonical[2] = "HI"
*/
const char* alternateStatesCanonical[] =
                                {   "CT",
                                    "DC",
                                    "HI", "HI",
                                    "LA",
                                    "MA", "MA", "MA", "MA",
                                    "MS", "MS", "MS", "MS", "MS", "MS", "MS", 
                                    "NH",
                                    "PA",
                                    "TN", "TN",
                                    "VA",
                                    "WV",
                                    "WI",
                                    "PE",
                                    "SK", "SK", "SK", 
                                    "NL", "NL",
                                    "NU", "NU", "NU"
                                };


// acceptable country names
const char * countries [] = {   "US",
                                "USA",
                                "United States",
                                "United States of America",
                                "Canada"
};


// common US cities
// taken from https://gist.github.com/norcal82/4accc0d968444859b408
// and https://en.wikipedia.org/wiki/List_of_the_largest_municipalities_in_Canada_by_population
// The US cities I reformatted so larger cities came earlier
// cities with periods are also included without, as they make up too little of the list
// to want to remove periods from the string before checking
const char * commonCities [] = {"Atlanta",
                                "Baltimore",
                                "Boston",
                                "Boulder",
                                "Buffalo",
                                "Charlotte",
                                "Chicago",
                                "Cincinnati",
                                "Cleveland",
                                "Dallas",
                                "Denver",
                                "Detroit",   
                                "Houston", 
                                "Jacksonville",
                                "Jefferson",
                                "Jersey City",
                                "Los Angeles",
                                "Memphis",
                                "Milwaukee",
                                "Minneapolis",
                                "Nashville",
                                "New Orleans",
                                "New York",
                                "New York City",
                                "Oakland",
                                "Orlando",
                                "Philadelphia",
                                "Phoenix",
                                "Portland",
                                "Raleigh",
                                "Sacramento",
                                "Saint Louis",
                                "Salt Lake City",
                                "San Antonio",
                                "San Diego",
                                "San Francisco",
                                "San Jose",
                                "Seattle",
                                "St. Louis",
                                "St Louis",
                                "Stockton",
                                "Tampa",
                                "Tucson",
                                "Tulsa",
                                "Toronto",
                                "Montreal",
                                "Calgary",
                                "Ottawa",
                                "Edmonton",
                                "Winnipeg",
                                "Mississauga",
                                "Vancouver",
                                // below cities have ~<400k population
                                "Akron",
                                "Albany",
                                "Albuquerque",
                                "Anaheim",
                                "Anchorage",
                                "Ann Arbor",
                                "Asheville",
                                "Athens",
                                "Atlantic City",
                                "Augusta",
                                "Austin",
                                "Bakersfield",
                                "Baton Rouge",
                                "Berkeley",
                                "Birmingham",
                                "Boise",
                                "Burbank",
                                "Burlington",
                                "Cambridge",
                                "Cedar Rapids",
                                "Charleston",
                                "Chattanooga",
                                "Columbus",
                                "Concord",
                                "Corpus Christi",
                                "Des Moines",
                                "El Paso",
                                "Fort Lauderdale",
                                "Fresno",
                                "Grand Rapids",
                                "Hartford",
                                "Indianapolis",
                                "Irvine",
                                "Irving",
                                "Jackson",
                                "Kansas City",
                                "Lansing",
                                "Las Vegas",
                                "Lexington",
                                "Lincoln",
                                "Little Rock",
                                "Long Beach",
                                "Louisville",
                                "Madison",
                                "Merced",
                                "Miami",
                                "Monterey",
                                "Montgomery",
                                "Myrtle Beach",
                                "Newark",
                                "Norfolk",
                                "Oklahoma City",
                                "Palm Springs",
                                "Pasadena",
                                "Peoria",
                                "Pittsburgh",
                                "Pomona",
                                "Port Saint Lucie",
                                "Port St. Lucie",
                                "Port St Lucie",
                                "Poughkeepsie",
                                "Providence",
                                "Provo",
                                "Rancho Cucamonga",
                                "Reno",
                                "Richmond",
                                "Rochester",
                                "Saint Paul",
                                "Saint Petersburg",
                                "San Bernardino",
                                "Santa Ana",
                                "Santa Barbara",
                                "Santa Clara",
                                "Santa Clarita",
                                "Santa Cruz",
                                "Savannah",
                                "Scottsdale",
                                "Scranton",
                                "Sioux Falls",
                                "Spokane",
                                "Springfield",
                                "St. Paul",
                                "St Paul",
                                "Sunnyvale",
                                "Syracuse",
                                "Tacoma",
                                "Tallahassee",
                                "Temecula",
                                "Tempe",
                                "Toledo",
                                "Topeka",
                                "Utica",
                                "Vallejo",
                                "Washington",
                                "Wichita",
                                "Wilmington",
                                "Yonkers",
                                // below cities have population <100k in general
                                "Aberdeen",
                                "Abilene",
                                "Alexandria",
                                "Allentown",
                                "Amarillo",
                                "Antioch",
                                "Apple Valley",
                                "Appleton",
                                "Arlington",
                                "Arvada",
                                "Aurora",
                                "Barnstable",
                                "Beaumont",
                                "Bel Air",
                                "Bellevue",
                                "Bethlehem",
                                "Billings",
                                "Bloomington",
                                "Boise City",
                                "Bonita Springs",
                                "Bradenton",
                                "Bremerton",
                                "Bridgeport",
                                "Brighton",
                                "Brownsville",
                                "Bryan",
                                "Canton",
                                "Cape Coral",
                                "Carrollton",
                                "Cary",
                                "Cathedral City",
                                "Champaign",
                                "Chandler",
                                "Chesapeake",
                                "Chula Vista",
                                "Clarke County",
                                "Clarksville",
                                "Clearwater",
                                "College Station",
                                "Colorado Springs",
                                "Columbia",
                                "Coral Springs",
                                "Corona",
                                "Costa Mesa",
                                "Daly City",
                                "Danbury",
                                "Davenport",
                                "Davidson County",
                                "Dayton",
                                "Daytona Beach",
                                "Deltona",
                                "Denton",
                                "Downey",
                                "Duluth",
                                "Durham",
                                "El Monte",
                                "Elizabeth",
                                "Elk Grove",
                                "Elkhart",
                                "Erie",
                                "Escondido",
                                "Eugene",
                                "Evansville",
                                "Fairfield",
                                "Fargo",
                                "Fayetteville",
                                "Fitchburg",
                                "Flint",
                                "Fontana",
                                "Fort Collins",
                                "Fort Smith",
                                "Fort Walton Beach",
                                "Fort Wayne",
                                "Fort Worth",
                                "Frederick",
                                "Fremont",
                                "Fullerton",
                                "Gainesville",
                                "Garden Grove",
                                "Garland",
                                "Gastonia",
                                "Gilbert",
                                "Glendale",
                                "Grand Prairie",
                                "Grayslake",
                                "Green Bay",
                                "Greensboro",
                                "Greenville",
                                "Gulfport-Biloxi",
                                "Hagerstown",
                                "Hampton",
                                "Harlingen",
                                "Harrisburg",
                                "Havre de Grace",
                                "Hayward",
                                "Hemet",
                                "Henderson",
                                "Hesperia",
                                "Hialeah",
                                "Hickory",
                                "High Point",
                                "Hollywood",
                                "Honolulu",
                                "Houma",
                                "Howell",
                                "Huntington",
                                "Huntington Beach",
                                "Huntsville",
                                "Independence",
                                "Inglewood",
                                "Johnson City",
                                "Joliet",
                                "Kailua",
                                "Kalamazoo",
                                "Kaneohe",
                                "Kennewick",
                                "Kenosha",
                                "Killeen",
                                "Kissimmee",
                                "Knoxville",
                                "Lacey",
                                "Lafayette",
                                "Lake Charles",
                                "Lakeland",
                                "Lakewood",
                                "Lancaster",
                                "Laredo",
                                "Las Cruces",
                                "Layton",
                                "Leominster",
                                "Lewisville",
                                "Lorain",
                                "Lowell",
                                "Lubbock",
                                "Macon",
                                "Manchester",
                                "Marina",
                                "Marysville",
                                "McAllen",
                                "McHenry",
                                "Medford",
                                "Melbourne",
                                "Mesa",
                                "Mesquite",
                                "Miramar",
                                "Mission Viejo",
                                "Mobile",
                                "Modesto",
                                "Monroe",
                                "Moreno Valley",
                                "Murfreesboro",
                                "Murrieta",
                                "Muskegon",
                                "Naperville",
                                "Naples",
                                "Nashua",
                                "New Bedford",
                                "New Haven",
                                "New London",
                                "Newburgh",
                                "Newport News",
                                "Normal",
                                "Norman",
                                "North Charleston",
                                "North Las Vegas",
                                "North Port",
                                "Norwalk",
                                "Norwich",
                                "Ocala",
                                "Oceanside",
                                "Odessa",
                                "Ogden",
                                "Olathe",
                                "Olympia",
                                "Omaha",
                                "Ontario",
                                "Orange",
                                "Orem",
                                "Overland Park",
                                "Oxnard",
                                "Palm Bay",
                                "Palmdale",
                                "Panama City",
                                "Paterson",
                                "Pembroke Pines",
                                "Pensacola",
                                "Plano",
                                "Pompano Beach",
                                "Port Arthur",
                                "Port Orange",
                                "Portsmouth",
                                "Pueblo",
                                "Punta Gorda",
                                "Racine",
                                "Reading",
                                "Redding",
                                "Richland",
                                "Richmond County",
                                "Riverside",
                                "Roanoke",
                                "Rockford",
                                "Roseville",
                                "Round Lake Beach",
                                "Saginaw",
                                "Salem",
                                "Salinas",
                                "San Buenaventura",
                                "Santa Maria",
                                "Santa Rosa",
                                "Sarasota",
                                "Seaside",
                                "Sebastian",
                                "Shreveport",
                                "Simi Valley",
                                "Sioux City",
                                "South Bend",
                                "South Lyon",
                                "Spartanburg",
                                "Springdale",
                                "St. Petersburg",
                                "St Petersburg",
                                "Stamford",
                                "Sterling Heights",
                                "Thornton",
                                "Thousand Oaks",
                                "Torrance",
                                "Trenton",
                                "Tuscaloosa",
                                "Tyler",
                                "Vero Beach",
                                "Victorville",
                                "Virginia Beach",
                                "Visalia",
                                "Waco",
                                "Warren",
                                "Waterbury",
                                "Waterloo",
                                "West Covina",
                                "West Valley City",
                                "Westminster",
                                "Winston",
                                "Winter Haven",
                                "Worcester",
                                "Yakima",
                                "York",
                                "Youngstown",
                                // Canadian cities, sorted by population
                                "Brampton",
                                "Hamilton",
                                "Surrey",
                                "Quebec City",
                                "Halifax",
                                "Laval",
                                "London",
                                "Markham",
                                "Vaughan",
                                "Gatineau",
                                "Saskatoon",
                                "Kitchener",
                                "Longueuil",
                                "Burnaby",
                                "Windsor",
                                "Regina",
                                "Oakville",
                                "Richmond Hill",
                                "Oshawa",
                                "Sherbrooke",
                                "Greater Sudbury",
                                "Abbotsford",
                                "Levis",
                                "Coquitlam",
                                "Barrie",
                                "Saguenay",
                                "Kelowna",
                                "Guelph",
                                "Trois-Rivieres",
                                "Whitby",
                                "St. Catharines",
                                "St Catharines",
                                "Milton",
                                "Langley",
                                "Kingston",
                                "Ajax",
                                "Terrebonne",
                                "Saanich",
                                "St. John\'s",
                                "St John\'s",
                                "Thunder Bay",
                                "Delta",
                                "Brantford",
                                "Chatham-Kent",
                                "Clarington",
                                "Red Deer",
                                "Nanaimo",
                                "Strathcona County",
                                "Pickering",
                                "Lethbridge",
                                "Kamloops",
                                "Saint-Jean-sur-Richelieu",
                                "Niagara Falls",
                                "Cape Breton",
                                "Chilliwack",
                                "Victoria",
                                "Brossard",
                                "Maple Ridge",
                                "Newmarket",
                                "Repentigny",
                                "Peterborough",
                                "Saint-Jerome",
                                "Moncton",
                                "Drummondville",
                                "Kawartha Lakes",
                                "New Westminster",
                                "Prince George",
                                "Caledon",
                                "Airdrie",
                                "Wood Buffalo",
                                "Sault Ste. Marie", //sufjan stevens!!
                                "Sault Ste Marie",
                                "Sarnia",
                                "Saint John",
                                "Granby",
                                "St. Albert",
                                "St Albert",
                                "Norfolk County",
                                "Grande Prairie",
                                "Medicine Hat",
                                "Fredericton",
                                "Halton Hills",
                                "Aurora",
                                "Port Coquitlam",
                                "Mirabel",
                                "Blainville",
                                "North Vancouver",
                                "Saint-Hyacinthe",
                                "Welland",
                                "Belleville",
                                "North Bay"
};


// indicators that a string might be a two-word major city
const char * multiCityTwoCues [] = {"Jersey",
                                    "Los",
                                    "New",
                                    "Saint",
                                    "San",
                                    "St.",
                                    "St",
                                    "Ann",
                                    "Atlantic",
                                    "Baton",
                                    "Cedar",
                                    "Corpus",
                                    "Des",
                                    "El",
                                    "Fort",
                                    "Grand",
                                    "Kansas",
                                    "Las",
                                    "Little",
                                    "Long",
                                    "Myrtle",
                                    "Oklahoma",
                                    "Palm",
                                    "Rancho",
                                    "Santa",
                                    "Sioux",
                                    "Apple",
                                    "Bel",
                                    "Boise",
                                    "Bonita",
                                    "Cape",
                                    "Cathedral",
                                    "Chula",
                                    "Clarke",
                                    "College",
                                    "Colorado",
                                    "Coral",
                                    "Costa",
                                    "Daly",
                                    "Davidson",
                                    "Daytona",
                                    "Elk",
                                    "Garden",
                                    "Green",
                                    "High",
                                    "Huntington",
                                    "Johnson",
                                    "Lake",
                                    "Mission",
                                    "Moreno",
                                    "Newport",
                                    "North",
                                    "Overland",
                                    "Panama",
                                    "Pembroke",
                                    "Pompano",
                                    "Port",
                                    "Punta",
                                    "Richmond",
                                    "Simi",
                                    "South",
                                    "Sterling",
                                    "Thousand",
                                    "Vero",
                                    "Virginia",
                                    "West",
                                    "Winter",
                                    "Quebec",
                                    "Greater",
                                    "Thunder",
                                    "Red",
                                    "Strathcona",
                                    "Niagara",
                                    "Maple",
                                    "Kawartha",
                                    "Prince",
                                    "Wood",
                                    "Norfolk",
                                    "Grande",
                                    "Medicine",
                                    "Halton",
};


// indicators that a string might be a three-word major city
const char* multiCityThreeCues [] = {
                                    "New",
                                    "Salt",
                                    "Port",
                                    "Fort",
                                    "Havre",
                                    "North",
                                    "Round",
                                    "West",
                                    "Sault",
};



// The following information is taken from https://github.com/0syntrax0/go-address-parser/blob/master/street.go,
// which is licensed under the following MIT License:

/*
    MIT License

    Copyright (c) 2020 Carlos A Saavedra

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
*/


const char* streetDirectionals [] = {   "N", "NORTH", "NORTE",
                                        "E", "EAST", "ESTE",
                                        "W", "WEST", "OESTE",
                                        "S", "SOUTH", "SUR",
                                        "NE", "NORTHEAST", "NORESTE",
                                        "NW", "NORTHWEST", "NOROESTE",
                                        "SE", "SOUTHEAST", "SURESTE",
                                        "SW", "SOUTHWEST", "SUROESTE"
                                        // please attach the above license if you are referring to
                                        // this list at all
                                    };

                                // the list provided sorted the list in alphabetical order,
                                // but I put the most common suffixes at the start for faster
                                // positive returns. Unfortunately, negative matches will still
                                // take a little while.
const char* streetSuffixes[] = {"ROAD", "RD", "STREET", "ST", "WAY", "WY", "AVENUE", "AVE",
                                "DRIVE", "DR", "LANE", "LN", "PLACE", "PL", "TERRACE", "TERR", "TER",
                                "PATH", "BOULEVARD", "BLVD", "COURT", "CT", "CRESCENT", "CRES",
                                "CIRCLE", "CIR", "HIGHWAY", "HWY", "PARKWAY", "PKWY", "AVENIDA", 
                                "CALLE", "CLL", "PASEO", "PSO", "VEREDA", "VER", "CERRADA", "CER", 
                                "CIRCULO", "CAMINO", "CAM",

                                // PLEASE INCLUDE THE ABOVE LICENSE IF YOU USE THIS LIST
                                // BECAUSE I DID NOT COMPILE IT MYSELF.
                                // you're free to just copy-paste it as a comment in the
                                // source code though, since this is open-source
    
                                "ALLEY", "ALY", "ALLY", "ANEX", "ANX", "ANNEX", "ANNX",
                                "ARCADE", "ARC", "AVEN", "AVENU", "AVN",
                                "AVNUE", "BAYOU", "BYU", "BEACH", "BCH", "BEND", "BND",
                                "BLUFF", "BLF", "BLUF", "BLUFFS", "BLFS", "BOTTOM", "BTM",
                                "BOT", "BOTTM", "BOUL", "BOULV", "BRANCH",
                                "BR", "BRNCH", "BRIDGE", "BRG", "BRDGE", "BROOK", "BRK", "BROOKS",
                                "BRKS", "BURG", "BG", "BURGS", "BGS", "BYPASS", "BYP", "BYPA",
                                "BYPAS", "BYPS", "CAMP", "CP", "CMP", "CANYON", "CYN", "CNYN",
                                "CAPE", "CPE", "CAUSEWAY", "CSWY", "CAUSWA", "CENTER", "CTR",
                                "CENT", "CENTR", "CENTRE", "CNTER", "CNTR", "CENTERS", "CTRS",
                                "CIRC", "CIRCL", "CRCL", "CRCLE", "CIRCLES",
                                "CIRS", "CLIFF", "CLF", "CLIFFS", "CLFS", "CLUB", "CLB", "COMMON",
                                "CMN", "COMMONS", "CMNS", "CORNER", "COR", "CORNERS", "CORS", "COURSE",
                                "CRSE", "COURTS", "CTS", "COVE", "CV", "COVES", "CVS",
                                "CREEK", "CRK",  "CRSENT", "CRSNT", "CREST", "CRST",
                                "CROSSING", "XING", "CRSSNG", "CROSSROAD", "XRD", "CROSSROADS", "XRDS",
                                "CURVE", "CURV", "DALE", "DL", "DAM", "DM", "DIVIDE", "DV", "DVD", "DIV",
                                "DRIV", "DRV", "DRIVES", "DRS", "ESTATE", "EST", "ESTATES",
                                "ESTS", "EXPRESSWAY", "EXPY", "EXPR", "EXPRESS", "EXPW", "EXTENSION", "EXT",
                                "EXTN", "EXTNSN", "EXTENSIONS", "EXTS", "FALL", "FALLS", "FLS", "FERRY",
                                "FRY", "FRRY", "FIELD", "FLD", "FIELDS", "FLDS", "FLAT", "FLT", "FLATS", "FLTS",
                                "FORD", "FRD", "FORDS", "FRDS", "FOREST", "FRST", "FORESTS", "FORGE",
                                "FRG", "FORGES", "FRGS", "FORK", "FRK", "FORKS", "FRKS", "FORT", "FT",
                                "FRT", "FREEWAY", "FWY", "FREEWY", "FRWAY", "FRWY", "GARDEN", "GDN",
                                "GARDN", "GRDEN", "GRDN", "GARDENS", "GDNS", "GRDNS", "GATEWAY", "GTWY",
                                "GATEWY", "GATWAY", "GTWAY", "GLEN", "GLN", "GLENS", "GLNS", "GREEN", "GRN",
                                "GREENS", "GRNS", "GROVE", "GRV", "GROV", "GROVES", "GRVS", "HARBOR", "HBR",
                                "HARB", "HARBR", "HRBOR", "HARBORS", "HBRS", "HAVEN", "HVN", "HEIGHTS",
                                "HTS", "HIGHWY", "HIWAY", "HIWY", "HWAY", "HILL",
                                "HL", "HILLS", "HLS", "HOLLOW", "HOLW", "HLLW", "HOLLOWS", "HOLWS",
                                "INLET", "INLT", "ISLAND", "IS", "ISLND", "ISLANDS", "ISS", "ISLNDS",
                                "ISLE", "ISLES", "JUNCTION", "JCT", "JCTION", "JCTN",
                                "JUNCTN", "JUNCTON", "JUNCTIONS", "JCTS", "JCTNS", "KEY", "KY", "KEYS",
                                "KYS", "KNOLL", "KNL", "KNOL", "KNOLLS", "KNLS", "LAKE", "LK", "LAKES",
                                "LKS", "LAND", "LANDING", "LNDG", "LNDNG", "LIGHT",
                                "LGT", "LIGHTS", "LGTS", "LOAF", "LF", "LOCK", "LCK", "LOCKS", "LCKS",
                                "LODGE", "LDG", "LDGE", "LODG", "LOOP","LOOPS", "MALL", 
                                "MANOR", "MNR", "MANORS", "MNRS", "MEADOW", "MDW", "MEADOWS", "MDWS",
                                "MEDOWS", "MEWS", "MILL", "ML", "MILLS", "MLS", "MISSION", "MSN",
                                "MSSN", "MISSN", "MOTORWAY", "MTWY", "MOUNT", "MT", "MNT", "MOUNTAIN",
                                "MTN", "MNTAIN", "MNTN", "MOUNTIN", "MTIN", "MOUNTAINS", "MTNS", "MNTNS",
                                "NECK", "NCK", "ORCHARD", "ORCH", "ORCHRD", "OVAL",  "OVL", "OVERPASS",
                                "OPAS", "PARK", "PRK", "PARKS",
                                // please make sure to include the provided license
                                "PARKWY", "PKWAY", "PKY", "PARKWAYS", "PKWYS", "PASS",
                                "PASSAGE", "PSGE", "PATHS", "PIKE",  "PIKES",
                                "PINE", "PNE", "PINES", "PNES", "PLACE", "PL", "PLAIN", "PLN", "PLAINS",
                                "PLNS", "PLAZA", "PLZ", "PLZA", "POINT", "PT", "POINTS", "PTS", "PORT",
                                "PRT", "PORTS", "PRTS", "PRAIRIE", "PR", "PRR", "RADIAL", "RADL", "RAD",
                                "RADIEL", "RAMP", "RANCH", "RNCH", "RANCHES", "RNCHS", "RAPID",
                                "RPD", "RAPIDS", "RPDS", "REST", "RST", "RIDGE", "RDG", "RDGE",
                                "RIDGES", "RDGS", "RIVER", "RIV", "RVR", "RIVR",
                                "ROADS", "RDS", "ROUTE", "RTE", "ROW", "RUE",
                                "RUN", "SHOAL", "SHL", "SHOALS", "SHLS", "SHORE", "SHR",
                                "SHOAR", "SHORES", "SHRS", "SHOARS", "SKYWAY", "SKWY", "SPRING", "SPG",
                                "SPNG", "SPRNG", "SPRINGS", "SPGS", "SPNGS", "SPRNGS", "SPUR",
                                "SPURS", "SPUR", "SQUARE", "SQ", "SQR", "SQRE", "SQU", "SQUARES",
                                "SQS", "SQRS", "STATION", "STA", "STATN", "STN", "STRAVENUE", "STRA",
                                "STRAV", "STRAVEN", "STRAVN", "STRVN", "STRVNUE", "STREAM", "STRM",
                                // sorry for adding all these comments I need them to be annoying
                                // to copy-paste into python to make sure you include the license
                                "STREME", "STRT", "STR", "STREETS", "STS", "SUMMIT",
                                "SMT", "SUMIT", "SUMITT", "TERRACE", "TER", "TERR", "THROUGHWAY", "TRWY",
                                "TRACE", "TRCE", "TRACES", "TRACK", "TRAK", "TRACKS", "TRK", "TRKS",
                                "TRAFFICWAY", "TRFY", "TRAIL", "TRL", "TRAILS", "TRLS", "TRAILER",
                                "TRLR", "TRLRS", "TUNNEL", "TUNL", "TUNEL", "TUNLS", "TUNNELS",
                                "TUNNL", "TURNPIKE", "TPKE", "TRNPK", "TURNPK", "UNDERPASS", "UPAS",
                                "UNION", "UN", "UNIONS", "UNS", "VALLEY", "VLY", "VALLY",
                                "VLLY", "VALLEYS", "VLYS", "VIADUCT", "VIA", "VDCT", "VIADCT",
                                "VIEW", "VW", "VIEWS", "VWS", "VILLAGE", "VLG",
                                "VILL", "VILLAG", "VILLG", "VILLIAGE", "VILLAGES", "VLGS", "VILLE",
                                "VL", "VISTA", "VIS", "VIST", "VST", "VSTA", "WALK", "WALK",
                                "WALKS", "WALL", "WAY", "WAYS",
                                "WELL", "WL", "WELLS", "WLS", 
                                // Spanish street suffixes
                                "CAMINITO", "CMT", "ENTRADA", "ENT",
                                "PLACITA", "PLA", "RANCHO", "RCH"
		
};



#endif